laser_: "/transformed_scan"
odom_: "/odom"
pose_: "/pose"
bumper_f_: "/pyro/base_f_bumper_sensor"
bumper_b_: "/pyro/base_b_bumper_sensor"
base_ref_: "/cmd_vel"
open_door_: "/pyro/open_door"
speak_: "/pyro/text_to_speech/input"
play_: "/text_to_speech/file"
base_link_: "internal/base_link"
